# Terraform Actions 역할과 target별 최소 권한을 계산한다.
locals {
  target_state_keys = {
    shared     = "shared/landit-iac/terraform.tfstate"
    develop    = "dev/landit-iac/terraform.tfstate"
    production = "prod/landit-iac/terraform.tfstate"
  }

  role_bindings = {
    for binding in setproduct(["plan", "apply"], keys(local.target_state_keys)) :
    "${binding[0]}-${binding[1]}" => {
      phase  = binding[0]
      target = binding[1]
    }
  }

  platform_read_actions = [
    "athena:GetNamedQuery",
    "athena:GetWorkGroup",
    "athena:ListTagsForResource",
    "ec2:DescribeAvailabilityZones",
    "ec2:DescribeInternetGateways",
    "ec2:DescribeRouteTables",
    "ec2:DescribeSecurityGroups",
    "ec2:DescribeSubnets",
    "ec2:DescribeVpcs",
    "ecr:DescribeRepositories",
    "ecr:GetLifecyclePolicy",
    "ecr:GetRepositoryPolicy",
    "ecr:ListTagsForResource",
    "ecs:DescribeClusters",
    "ecs:DescribeServices",
    "ecs:DescribeTaskDefinition",
    "ecs:ListTagsForResource",
    "elasticloadbalancing:DescribeListeners",
    "elasticloadbalancing:DescribeLoadBalancers",
    "elasticloadbalancing:DescribeRules",
    "elasticloadbalancing:DescribeTags",
    "elasticloadbalancing:DescribeTargetGroups",
    "firehose:DescribeDeliveryStream",
    "firehose:ListTagsForDeliveryStream",
    "glue:GetDatabase",
    "glue:GetTable",
    "glue:GetTags",
    "iam:GetInstanceProfile",
    "iam:GetRole",
    "iam:GetRolePolicy",
    "iam:ListAttachedRolePolicies",
    "iam:ListInstanceProfilesForRole",
    "iam:ListRolePolicies",
    "logs:DescribeLogGroups",
    "logs:DescribeSubscriptionFilters",
    "logs:ListTagsForResource",
    "s3:GetBucketAcl",
    "s3:GetBucketCors",
    "s3:GetBucketLifecycleConfiguration",
    "s3:GetBucketLocation",
    "s3:GetBucketLogging",
    "s3:GetBucketNotification",
    "s3:GetBucketOwnershipControls",
    "s3:GetBucketPolicy",
    "s3:GetBucketPolicyStatus",
    "s3:GetBucketPublicAccessBlock",
    "s3:GetBucketTagging",
    "s3:GetBucketVersioning",
    "s3:GetEncryptionConfiguration",
    "s3:ListAllMyBuckets",
    "sqs:GetQueueAttributes",
    "sqs:GetQueueUrl",
    "sqs:ListQueueTags",
    "sts:GetCallerIdentity",
    "wafv2:GetLoggingConfiguration",
    "wafv2:GetWebACL",
    "wafv2:GetWebACLForResource",
    "wafv2:ListTagsForResource"
  ]

  read_actions_by_target = {
    shared = [
      "cloudfront:GetDistribution",
      "cloudfront:GetDistributionConfig",
      "cloudfront:GetOriginAccessControl",
      "cloudfront:ListTagsForResource",
      "s3:GetBucketAcl",
      "s3:GetBucketCors",
      "s3:GetBucketLocation",
      "s3:GetBucketPolicy",
      "s3:GetBucketPublicAccessBlock",
      "s3:GetBucketTagging",
      "s3:GetBucketVersioning",
      "s3:GetEncryptionConfiguration",
      "s3:ListAllMyBuckets",
      "sts:GetCallerIdentity"
    ]
    develop = concat(local.platform_read_actions, [
      "ec2:DescribeAddresses",
      "ec2:DescribeInstances",
      "ec2:DescribeTags",
      "ssm:DescribeDocument",
      "ssm:GetDocument",
      "ssm:GetParameter",
      "ssm:ListTagsForResource"
    ])
    production = concat(local.platform_read_actions, [
      "apigateway:GET",
      "lambda:GetFunction",
      "lambda:GetFunctionEventInvokeConfig",
      "lambda:GetPolicy",
      "lambda:ListTags"
    ])
  }

  platform_apply_actions = [
    "athena:CreateNamedQuery",
    "athena:CreateWorkGroup",
    "athena:DeleteNamedQuery",
    "athena:DeleteWorkGroup",
    "athena:TagResource",
    "athena:UntagResource",
    "athena:UpdateWorkGroup",
    "ec2:AssociateRouteTable",
    "ec2:AttachInternetGateway",
    "ec2:AuthorizeSecurityGroupEgress",
    "ec2:AuthorizeSecurityGroupIngress",
    "ec2:CreateInternetGateway",
    "ec2:CreateRoute",
    "ec2:CreateRouteTable",
    "ec2:CreateSecurityGroup",
    "ec2:CreateSubnet",
    "ec2:CreateTags",
    "ec2:CreateVpc",
    "ec2:DeleteInternetGateway",
    "ec2:DeleteRoute",
    "ec2:DeleteRouteTable",
    "ec2:DeleteSecurityGroup",
    "ec2:DeleteSubnet",
    "ec2:DeleteTags",
    "ec2:DeleteVpc",
    "ec2:DetachInternetGateway",
    "ec2:DisassociateRouteTable",
    "ec2:ModifySubnetAttribute",
    "ec2:ModifyVpcAttribute",
    "ec2:RevokeSecurityGroupEgress",
    "ec2:RevokeSecurityGroupIngress",
    "ecr:CreateRepository",
    "ecr:DeleteLifecyclePolicy",
    "ecr:DeleteRepository",
    "ecr:DeleteRepositoryPolicy",
    "ecr:PutLifecyclePolicy",
    "ecr:SetRepositoryPolicy",
    "ecr:TagResource",
    "ecr:UntagResource",
    "ecs:CreateCluster",
    "ecs:CreateService",
    "ecs:DeleteCluster",
    "ecs:DeleteService",
    "ecs:DeregisterTaskDefinition",
    "ecs:RegisterTaskDefinition",
    "ecs:TagResource",
    "ecs:UntagResource",
    "ecs:UpdateClusterSettings",
    "ecs:UpdateService",
    "elasticloadbalancing:AddTags",
    "elasticloadbalancing:CreateListener",
    "elasticloadbalancing:CreateLoadBalancer",
    "elasticloadbalancing:CreateRule",
    "elasticloadbalancing:CreateTargetGroup",
    "elasticloadbalancing:DeleteListener",
    "elasticloadbalancing:DeleteLoadBalancer",
    "elasticloadbalancing:DeleteRule",
    "elasticloadbalancing:DeleteTargetGroup",
    "elasticloadbalancing:ModifyListener",
    "elasticloadbalancing:ModifyLoadBalancerAttributes",
    "elasticloadbalancing:ModifyRule",
    "elasticloadbalancing:ModifyTargetGroup",
    "elasticloadbalancing:ModifyTargetGroupAttributes",
    "elasticloadbalancing:RemoveTags",
    "firehose:CreateDeliveryStream",
    "firehose:DeleteDeliveryStream",
    "firehose:StartDeliveryStreamEncryption",
    "firehose:StopDeliveryStreamEncryption",
    "firehose:TagDeliveryStream",
    "firehose:UntagDeliveryStream",
    "firehose:UpdateDestination",
    "glue:CreateDatabase",
    "glue:CreateTable",
    "glue:DeleteDatabase",
    "glue:DeleteTable",
    "glue:TagResource",
    "glue:UntagResource",
    "glue:UpdateDatabase",
    "glue:UpdateTable",
    "iam:AddRoleToInstanceProfile",
    "iam:AttachRolePolicy",
    "iam:CreateInstanceProfile",
    "iam:CreateRole",
    "iam:DeleteInstanceProfile",
    "iam:DeleteRole",
    "iam:DeleteRolePolicy",
    "iam:DetachRolePolicy",
    "iam:PutRolePolicy",
    "iam:RemoveRoleFromInstanceProfile",
    "iam:TagRole",
    "iam:UntagRole",
    "iam:UpdateAssumeRolePolicy",
    "logs:CreateLogGroup",
    "logs:DeleteLogGroup",
    "logs:DeleteSubscriptionFilter",
    "logs:PutRetentionPolicy",
    "logs:PutSubscriptionFilter",
    "logs:TagResource",
    "logs:UntagResource",
    "s3:CreateBucket",
    "s3:DeleteBucket",
    "s3:DeleteBucketLifecycle",
    "s3:DeleteBucketPolicy",
    "s3:DeleteBucketPublicAccessBlock",
    "s3:PutBucketLifecycleConfiguration",
    "s3:PutBucketPolicy",
    "s3:PutBucketPublicAccessBlock",
    "s3:PutBucketTagging",
    "s3:PutBucketVersioning",
    "s3:PutEncryptionConfiguration",
    "sqs:CreateQueue",
    "sqs:DeleteQueue",
    "sqs:SetQueueAttributes",
    "sqs:TagQueue",
    "sqs:UntagQueue",
    "wafv2:AssociateWebACL",
    "wafv2:CreateWebACL",
    "wafv2:DeleteLoggingConfiguration",
    "wafv2:DeleteWebACL",
    "wafv2:DisassociateWebACL",
    "wafv2:PutLoggingConfiguration",
    "wafv2:TagResource",
    "wafv2:UntagResource",
    "wafv2:UpdateWebACL"
  ]

  apply_actions_by_target = {
    shared = [
      "cloudfront:CreateDistribution",
      "cloudfront:CreateOriginAccessControl",
      "cloudfront:DeleteDistribution",
      "cloudfront:DeleteOriginAccessControl",
      "cloudfront:TagResource",
      "cloudfront:UntagResource",
      "cloudfront:UpdateDistribution",
      "cloudfront:UpdateOriginAccessControl",
      "s3:CreateBucket",
      "s3:DeleteBucket",
      "s3:DeleteBucketCors",
      "s3:DeleteBucketPolicy",
      "s3:DeleteBucketPublicAccessBlock",
      "s3:PutBucketCors",
      "s3:PutBucketPolicy",
      "s3:PutBucketPublicAccessBlock",
      "s3:PutBucketTagging",
      "s3:PutBucketVersioning",
      "s3:PutEncryptionConfiguration"
    ]
    develop = concat(local.platform_apply_actions, [
      "ec2:AllocateAddress",
      "ec2:AssociateAddress",
      "ec2:DisassociateAddress",
      "ec2:ModifyInstanceAttribute",
      "ec2:ReleaseAddress",
      "ec2:RunInstances",
      "ec2:TerminateInstances",
      "ssm:AddTagsToResource",
      "ssm:CreateDocument",
      "ssm:DeleteDocument",
      "ssm:RemoveTagsFromResource",
      "ssm:UpdateDocument",
      "ssm:UpdateDocumentDefaultVersion"
    ])
    production = concat(local.platform_apply_actions, [
      "apigateway:DELETE",
      "apigateway:PATCH",
      "apigateway:POST",
      "apigateway:PUT",
      "lambda:AddPermission",
      "lambda:CreateFunction",
      "lambda:DeleteFunction",
      "lambda:DeleteFunctionEventInvokeConfig",
      "lambda:RemovePermission",
      "lambda:TagResource",
      "lambda:UntagResource",
      "lambda:UpdateFunctionCode",
      "lambda:UpdateFunctionConfiguration",
      "lambda:PutFunctionEventInvokeConfig"
    ])
  }

  pass_role_services = [
    "ec2.amazonaws.com",
    "ecs-tasks.amazonaws.com",
    "firehose.amazonaws.com",
    "lambda.amazonaws.com"
  ]

  common_tags = {
    Project    = var.project_name
    ManagedBy  = "terraform"
    Repository = var.github_repository
    Purpose    = "terraform-actions-oidc"
  }
}
